version: '3,2'

networks:
  blog-network:
    driver: bridge

services:
  mysql:
    image: arm64v8/mysql:8.0.31
    container_name: mysql
    volumes:
      - ./data/db_data:/var/lib/mysql
      - ./config/mysql/init:/docker-entrypoint-initdb.d/
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      '--default-time-zone=+8:00'
    ]
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog
      MYSQL_USER: blog
      MYSQL_PASSWORD: blog123!@#
    ports:
      - 3306:3306
    networks:
      -  blog-network
  redis:
    container_name: redis
    image: arm64v8/redis:alpine
    ports:
      - 6379:6379
    networks:
      - blog-network
# docker-compose

